### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by Tbaut** [tien/dot-connect#46]
Hey Tien after integrating dotconnect in a hackaton project, here's a list of things I'd love to have
- I'd like to be able to totally control the opening and closing of the modal. For this, we have the `isOpen` but there's no `onClose` callback. I'm not sure if this is possible with web components.

- Another somewhat specific need I'd have in our app: I'd like to be able to select a specific account in a 2nd step, after having selected an extension. This way, if users have shared several accounts, they can select the one they want the interface to take into account. This would probably mean we'd need a `selectedAccount` in the fields of `useAccounts`. This may be a too specific ask though.

In any case, thank you for this, it's been very helpful

**Comment by tien** [comment]
Thanks for the feedback @Tbaut 

- The missing `onClose` callback is an oversight on my part, will get this resolved ASAP.
- For the `selectedAccount` feature, I have thought about including that before, but came to the conclusion that user most of the time would be better off creating their own account selection logic. Because there are so many different possibles' implementation (i.e single selection, multi-selection, different selection per page, etc). A bare-boned off the shelf solution might still prove useful, though, so I'll rethink this.

**Comment by Tbaut** [comment]
Thanks a lot.
I understand that it's not for every Dapp.

**Comment by tien** [comment]
- Controlled dialog is resolved by #47
- Possible opinionated hooks for active account(s) is moved to tien/reactive-dot#141
